# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='purchased',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
