# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_auto_20160830_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='habitat',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='zoo.Habitat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='habitat',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='zoo.Habitat'),
        ),
    ]
