# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_auto_20160830_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='habitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='zoo.Habitat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='habitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='zoo.Habitat'),
        ),
    ]
