# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zoo', '0005_auto_20160831_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='zoo.Habitat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
