# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0008_auto_20160915_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
